[package]
name = "give_me_tables"
version = "0.1.0"
authors = ["Stanko Krtalić <stanko.krtalic@gmail.com>"]

[dependencies]
serde = "1.0.8"
serde_json = "1.0.2"
clap = "2.22.1"
log = "0.3.7"
log4rs = "0.6.2"
